# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build C filesystem

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install libfuse-dev
        run: sudo apt-get install libfuse-dev
      - name: Run Makefile
        run: cd fs && make
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: tabfs
          path: |
            /home/runner/work/TabFS/TabFS/fs/tabfs
            /home/runner/work/TabFS/TabFS/install.sh
