# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Declare some variables
    id: vars
    shell: bash
    run: |
      echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --global web-ext
    - run: web-ext build -s extension -n tabfs

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: tabfs-${{ steps.vars.outputs.sha_short }}
        path: /home/runner/work/TabFS/TabFS/web-ext-artifacts/tabfs.zip
